=== Gerrri/DB2/ARTIKEL1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	 <xsd:element name="TABLE">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ARTIKEL"  maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:sequence>
									<xsd:element name="ARTNR" type="xsd:int"></xsd:element>
									<xsd:element name="ARTBEZ" type="xsd:string"></xsd:element>
									<xsd:element name="MGE" type="xsd:string"></xsd:element>
									<xsd:element name="PREIS" type="xsd:double"></xsd:element>
									<xsd:element name="KUEHL" type="xsd:string"></xsd:element>
									<xsd:element name="EDAT" type="xsd:string"></xsd:element>
							</xsd:sequence>
						</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="NAME" type="xsd:string"></xsd:attribute>
		</xsd:complexType>
	 </xsd:element>
</xsd:schema>

=== Gerrri/DB2/ARTIKEL1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<TABLE NAME="ALLEARTIKEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ARTIKEL1.XSD">
  
    <ARTIKEL>
        <ARTNR>101</ARTNR>
        <ARTBEZ>Deo12</ARTBEZ>
        <MGE>stk</MGE>
        <PREIS>1.29</PREIS>
        <KUEHL>NK</KUEHL>
        <EDAT>2017-12-02</EDAT>
    </ARTIKEL>

    <ARTIKEL>
        <ARTNR>3</ARTNR>
        <ARTBEZ>Toast12</ARTBEZ>
        <MGE>kg</MGE>
        <PREIS>3.99</PREIS>
        <KUEHL>NK</KUEHL>
        <EDAT>2001-01-01</EDAT>
    </ARTIKEL>
</TABLE>
