=== Gerrri/DB2/Bestellung.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	 <xs:element name="TABLE">
		<xs:attribute name="NAME" type="xs:string"></xs:attribute>
		   <xs:complexType>
				 <xs:sequence>
					   <xs:element name="BESTELLUNG">
							 <xs:complexType>
								   <xs:sequence>
										 <xs:element name="KNR" type="xs:int"></xs:element>
										 <xs:element name="STATUS" type="xs:string"></xs:element>
										 <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="ARTNR" type="xs:int"></xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
								   </xs:sequence>
							 </xs:complexType>
					   </xs:element>
				 </xs:sequence>
		   </xs:complexType>
	 </xs:element>
</xs:schema>

=== Gerrri/DB2/Bestellung.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<TABLE NAME="BESTELLUNG2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Bestellung.XSD">
    <BESTELLUNG>
		<KNR>3</KNR>
		<STATUS>1</STATUS>
		<ARTNR>1</ARTNR>
		<ARTNR>2</ARTNR>
		<ARTNR>1</ARTNR>
		<ARTNR>1</ARTNR>
	</BESTELLUNG>
</TABLE>
